accounts/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'

urlpatterns = [
    url(r'^insertnick/', views.insertnick, name='insertnick'),
    url(r'^userdata/', views.userdata, name='userdata'),
    url(r'^play/', views.play, name='play'),
    url(r'^results/', views.results, name='results'),
]

proyectoHads/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from quizzes import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^quizzes/', include('quizzes.urls')),
    url(r'^game/', include('game.urls')),
    url(r'^$', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

quizzes/urls.py
from django.conf.urls import url
from . import views

app_name = 'quizzes'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^allquizzes/', views.allquizzes, name='allquizzes'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Quizzes</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav" >
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Quizzes</a>
                <ul class="nav navbar-nav navbar-left">
                {% if user.is_authenticated %}
                    <li><a  href="{% url 'quizzes:create' %}">Insertar pregunta</a></li>
                    <li><a  href="{% url 'quizzes:allquizzes' %}">Ver preguntas</a></li>
                {% else %}
                    <li><a  href="{% url 'game:insertnick' %}">Responder preguntas</a></li>
                {% endif %}
                </ul>
            </div>
             <div class="collapse navbar-collapse" id="mynav">
                 <ul class="nav navbar-nav navbar-right">
                     {% if user.is_authenticated %}
                     <li><a href="#" onClick="document.getElementById('logout').submit()">Cerrar Sesión</a></li>
                     <form id="logout" action="{% url 'accounts:logout'%}" method="post">
                         {% csrf_token %}
                         <input type="hidden"/>
                     </form>
                     {% else %}
                        <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Resgístrate</a></li>
                        <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Iniciar Sesión</a></li>
                     {% endif %}

                 </ul>
             </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <br/><br/><br/>
    <footer class="navbar navbar-default navbar-fixed-bottom" >
        <div class="container" style="">
              <ul class="nav navbar-nav navbar-left">
                  <li><a href="https://github.com/berrio86">Creado por Iñaki Berriotxoa</a></li>
              </ul>
        {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"> Nombre de usuario: {{ user.username }} </a> </li>
                <li><img src="/media/{{ user.avatar.picture }}" class="img-responsive" style="max-height:55px;"/></li>
            </ul>
        {% endif %}
        </div>

    </footer>
    <!-- añadiendo comportamiento ajax-->
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    {% block javascript %}{% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>