game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'

urlpatterns = [
    url(r'^insertnick/', views.insertnick, name='insertnick'),
    url(r'^userdata/', views.userdata, name='userdata'),
    url(r'^play/', views.play, name='play'),
    url(r'^results/', views.results, name='results'),
]

proyectoHads/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from quizzes import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^quizzes/', include('quizzes.urls')),
    url(r'^game/', include('game.urls')),
    url(r'^$', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

game/models.py
from django.db import models


class Player(models.Model):
    respuestas_correctas = models.IntegerField(default=0)
    respuestas_incorrectas = models.IntegerField(default=0)
    nick = models.TextField()


    def preguntasTotales(self):
        return self.respuestas_correctas + self.respuestas_incorrectas

    def porcentajeCorrecto(self):
        return round((100 * self.respuestas_correctas)/self.preguntasTotales(), 2)

    def porcentajeIncorrecto(self):
        return round((100 * self.respuestas_incorrectas)/self.preguntasTotales(),2)

game/views.py
from django.shortcuts import render, redirect
from .models import Player
from quizzes.models import Quizz
from quizzes.models import Topic

def insertnick(request):
    return render(request, 'game/insertnick.html')

def userdata(request):
    if request.method == 'POST':
        if request.POST['nick']:
            # intentar recuperar todos los temas diferentes de los modelos Quizz y pasarlos como set
            try:
                player = Player.objects.get(nick=request.POST['nick'])
                temas = Topic.objects.all()
                return render(request, 'game/userdata.html', {'ok': 'Tu usuario ha sido cargado de forma correcta.', 'player': player, 'temas': temas})
            except Player.DoesNotExist:
                nick= request.POST['nick']
                player=Player()
                player.nick = nick
                player.respuestas_incorrectas = 0
                player.respuestas_correctas = 0
                player.save()
                temas = Topic.objects.all()
                return render(request, 'game/userdata.html', {'ok': 'Se ha creado un nuevo usuario con el nick proporcionado' , 'player': player,'temas': temas})

            return render(request, 'game/userdata.html')
        else:
            return render(request, 'game/insertnick.html', {'error':'ERROR: Debe introducir un nick'})
    else:
        return render(request, 'game/insertnick.html')

def play(request):
    if request.method == 'POST':
        tema = request.POST['tema']
        nick = request.POST['nick']
        if tema == 'Todas':
            quizzes = Quizz.objects.all()
        else:
            tema_obj = Topic.objects.get(tema=request.POST['tema'])
            quizzes = Quizz.objects.filter(tema=tema_obj)
        return render(request, 'game/play.html', {'quizzes': quizzes, 'tema': tema, 'nick': nick })
    else:
        return render(request, 'game/insertnick.html')


def results(request):
    if request.method == 'POST':
        acertadas = 0
        falladas = 0
        tema = request.POST['tema']
        player = Player.objects.get(nick=request.POST['nick'])

        if tema == 'Todas':
            quizzes = Quizz.objects.all()
        else:
            tema_obj = Topic.objects.get(tema=request.POST['tema'])
            quizzes = Quizz.objects.filter(tema=tema_obj)

        total = len(quizzes)

        for quizz in quizzes:
            ru = request.POST[quizz.pregunta]
            rc = quizz.respuesta_correcta
            ru = int(ru)
            if rc == ru:
                acertadas = acertadas + 1
            else:
                falladas = falladas + 1

        player.respuestas_correctas = player.respuestas_correctas + acertadas
        player.respuestas_incorrectas = player.respuestas_incorrectas + falladas
        player.save()

        return render(request, 'game/results.html', {'total': total, 'player': player, 'falladas': falladas, 'acertadas':acertadas})
    else:
        return render(request, 'game/insertnick.html')

game/templates/game/insertnick.html
{% extends 'base.html' %}
{% block content%}

<h1>Introduzca un nick</h1><br/><br/>

<p> Al introducir su nick podrá guardar el total de fallos y aciertos en todas las partidas.</p><br/>

{% if error %}
    <div class="alert alert-danger" role="alert"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {{ error }} </div>  <br/>
{% endif %}

<form action="{% url 'game:userdata'%}" method="post">
        {% csrf_token %}


        Nick para guardar sus partidas: <br/><br/>
        <input type="text" name="nick" /> <br/><br/>


        <input type="submit" value="Introducir nick" class="btn btn-primary"/><br/><br/>


</form>

{% endblock %}

game/templates/game/play.html
{% extends 'base.html' %}
{% block content%}

<h1>¡Hagan juego!</h1><br/><br/>


<form action="{% url 'game:results' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="tema" value="{{ tema }}"/>
    <input type="hidden" name="nick" value="{{ nick }}"/>

    {% for quizz in quizzes.all %}

    <h3>{{ quizz.pregunta }}</h3>


    <input type="radio" name="{{ quizz.pregunta }}" value="1" checked /> {{ quizz.respuesta1 }}<br/>
    <input type="radio" name="{{ quizz.pregunta }}" value="2" /> {{ quizz.respuesta2 }}<br/>
    <input type="radio" name="{{ quizz.pregunta }}" value="3"/> {{ quizz.respuesta3 }} <br/><br/>

    <hr/>
    {% endfor %}

    <input type="submit" value="Ver resultados" class="btn btn-primary"/><br/><br/>
</form>





{% endblock %}

game/templates/game/results.html
{% extends 'base.html' %}
{% block content%}

<h1>Resultados</h1><br/><br/>

<h2>{{ player.nick }}</h2><br/>




<h3>Resultados de esta serie:</h3><br/>



<table class="table">
        <tr>
            <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Respuestas acertadas: </td>
            <td> {{ acertadas }} </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>  Respuestas falladas:</td>
            <td>{{ falladas }}</td>
        </tr>
        <tr>
            <td> Total: </td>
            <td> {{ total }} </td>
        </tr>
</table>


<h3>Resultados totales:</h3>
<table class="table">
        <tr>
            <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Respuestas acertadas: </td>
            <td> {{ player.respuestas_correctas }} </td>
            <td> {{ player.porcentajeCorrecto }} % </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>  Respuestas falladas:</td>
            <td>{{ player.respuestas_incorrectas }}</td>
            <td>{{ player.porcentajeIncorrecto }} % </td>
        </tr>
        <tr>
            <td> Total: </td>
            <td> {{ player.preguntasTotales }} </td>
            <td> </td>
        </tr>
</table>

<form method="post" action="{% url 'game:userdata' %}">
    {% csrf_token %}
    <input type="hidden" name="nick" value="{{ player.nick }}"/>
    <input type="submit" value="Jugar otra vez" class="btn btn-primary"/><br/><br/>
</form>


{% endblock %}

game/templates/game/userdata.html
{% extends 'base.html' %}
{% block content%}


<h1> Datos de usuario </h1>

{% if ok %}
<div class="alert alert-success" role="alert"> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> {{ ok }} </div>
{% endif %}

<hr/>

{% if player %}

<h2>{{ player.nick }}</h2><br/>

<table class="table">
        <tr>
            <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Respuestas acertadas: </td>
            <td> {{ player.respuestas_correctas }} </td>
        </tr>
        <tr>
            <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>  Respuestas falladas:</td>
            <td>{{ player.respuestas_incorrectas }}</td>
        </tr>
        <tr>
            <td> Total: </td>
            <td> {{ player.preguntasTotales }} </td>
        </tr>
</table>



{% endif %}

<hr/>

<form action="{% url 'game:play' %}" method="post">
        {% csrf_token %}

        <input type="hidden" name='nick' value="{{ player.nick }}"/>
        Seleccione el tema: <br/><br/>

        {% for tema in temas.all %}

        <input type="radio" name="tema" value="{{ tema.tema }}" > {{ tema.tema }}<br/>


        {% endfor %}
        <input type="radio" name="tema" value="Todas" checked> Todas <br/><br/>

        <input type="submit" value="Iniciar partida" class="btn btn-primary"/><br/><br/>


</form>

<hr/>


{% if tema %}


<h1>Enseñamos preguntas</h1>

{% endif %}

{% endblock %}